fix: apparmor securityfs fix

diff --git a/task2/daemonscript b/task2/daemonscript
--- a/task2/daemonscript
+++ b/task2/daemonscript
@@ -1,4 +1,23 @@
 #!/bin/bash
+CGROUP=/sys/fs/cgroup
+
+[ -d $CGROUP ] ||
+	mkdir $CGROUP
+
+mountpoint -q $CGROUP ||
+	mount -n -t tmpfs -o uid=0,gid=0,mode=0755 cgroup $CGROUP || {
+		echo "Could not make a tmpfs mount. Did you use --privileged?"
+		exit 1
+	}
+
+if [ -d /sys/kernel/security ] && ! mountpoint -q /sys/kernel/security
+then
+    mount -t securityfs none /sys/kernel/security || {
+        echo "Could not mount /sys/kernel/security."
+        echo "AppArmor detection and --privileged mode might break."
+    }
+fi
+
 dockerd &
 (( timeout = 60 + SECONDS ))
 until docker info >/dev/null 2>&1
@@ -9,4 +28,3 @@ do
 	fi
 	sleep 1
 done
-exec bash --login
